# Generated by Django 5.2.8 on 2025-12-21 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('order', 'Order'), ('order_cook', 'Order (Cook)'), ('order_courier', 'Order (Courier)'), ('chat', 'Chat'), ('review', 'Review'), ('manual', 'Manual')], db_index=True, default='manual', max_length=20),
        ),
    ]
