# Generated by Django 5.2.8 on 2025-12-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_lead_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
