# Generated by Django 5.2.8 on 2025-11-27 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_remove_product_category_product_categories_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_name',
        ),
        migrations.AddField(
            model_name='order',
            name='apartment',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Квартира'),
        ),
        migrations.AddField(
            model_name='order',
            name='courier_comment',
            field=models.TextField(blank=True, default='', verbose_name='Комментарий курьеру'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_first_name',
            field=models.CharField(default='', max_length=100, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_last_name',
            field=models.CharField(default='', max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='order',
            name='entrance',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Подъезд'),
        ),
        migrations.AddField(
            model_name='order',
            name='street',
            field=models.CharField(default='', max_length=200, verbose_name='Улица'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(default='', max_length=20, verbose_name='Телефон'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('street', models.CharField(max_length=200, verbose_name='Улица')),
                ('entrance', models.CharField(blank=True, max_length=10, verbose_name='Подъезд')),
                ('apartment', models.CharField(blank=True, max_length=10, verbose_name='Квартира')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
    ]
