# Generated by Django 5.2.8 on 2025-11-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0004_update_reviews_and_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="reviews/", verbose_name="Фото"
            ),
        ),
    ]
