# Generated by Django 5.2.8 on 2025-11-28 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0005_review_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="admin_comment",
            field=models.TextField(
                blank=True, default="", verbose_name="Комментарий администратора"
            ),
        ),
    ]
