# Generated by Django 5.2.8 on 2025-11-29 16:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0007_alter_review_unique_together_addon_size"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="addon",
            name="product",
        ),
        migrations.AddField(
            model_name="product",
            name="addons",
            field=models.ManyToManyField(
                blank=True,
                related_name="products",
                to="webapp.addon",
                verbose_name="Добавки",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="drinks_price_05",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Цена 0.5 л",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="drinks_price_1",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Цена 1 л",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="pizza_price_25",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Цена 25 см",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="pizza_price_30",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Цена 30 см",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="pizza_price_35",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Цена 35 см",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="discount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Скидка (%)",
            ),
        ),
    ]
