# Generated by Django 5.2.8 on 2025-12-03 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0009_chat_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="addons_info",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Добавки (список ID)"
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="size",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="webapp.size",
                verbose_name="Размер",
            ),
        ),
    ]
