# Generated by Django 5.2.8 on 2025-12-08 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0010_orderitem_addons_info_orderitem_size"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="drinks_price_05",
        ),
        migrations.RemoveField(
            model_name="product",
            name="drinks_price_1",
        ),
        migrations.RemoveField(
            model_name="product",
            name="pizza_price_25",
        ),
        migrations.RemoveField(
            model_name="product",
            name="pizza_price_30",
        ),
        migrations.RemoveField(
            model_name="product",
            name="pizza_price_35",
        ),
        migrations.RemoveField(
            model_name="product",
            name="price",
        ),
    ]
