# Generated by Django on 2025-12-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0011_remove_product_drinks_price_05_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_price',
            field=models.DecimalField(default=0, max_digits=10, decimal_places=2, verbose_name='Стоимость доставки'),
        ),
    ]
