# Generated by assistant to add token to Chat
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_add_delivery_price_to_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='token',
            field=models.CharField(max_length=64, null=True, blank=True, verbose_name='Client token'),
        ),
    ]
