# Generated by Django 5.2.8 on 2025-12-19 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0015_order_bonus_earned_order_bonus_used_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="average_rating",
            field=models.FloatField(default=0, verbose_name="Средний рейтинг"),
        ),
        migrations.AddField(
            model_name="product",
            name="is_hit",
            field=models.BooleanField(default=False, verbose_name="Хит продаж"),
        ),
        migrations.AddField(
            model_name="product",
            name="is_new",
            field=models.BooleanField(default=False, verbose_name="Новинка"),
        ),
        migrations.AddField(
            model_name="product",
            name="reviews_count",
            field=models.IntegerField(default=0, verbose_name="Количество отзывов"),
        ),
    ]
