# Generated by Django 5.2.8 on 2025-12-21 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_product_average_rating_product_is_hit_product_is_new_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('cooking', 'Готовится'), ('delivering', 'Доставляется'), ('completed', 'Завершен'), ('cancelled', 'Отменен')], default='new', max_length=20, verbose_name='Статус'),
        ),
    ]
